framework:
    messenger:
        transports:
            business_event:
                dsn: 'gps:'
                options:
                    project_id: '%env(PUBSUB_PROJECT_ID)%'
                    topic_name: '%env(PUBSUB_TOPIC_BUSINESS_EVENT)%'
                    subscription_name: '%env(PUBSUB_SUBSCRIPTION_WEBHOOK)%'
                # serializer: null
                # retry_strategy:
                #     service: null
                #     max_retries: 3
                #     delay: 1000
                #     multiplier: 2
                #     max_delay: 0

        routing:
            'Akeneo\Pim\Enrichment\Bundle\Message\BusinessEvent': business_event

        # serializer:
        #     default_serializer: messenger.transport.native_php_serializer
        #     symfony_serializer:
        #         format: json
        #         context: {  }

        # failure_transport: null

        # default_bus: null
        # buses:
        #     messenger.bus.default:
        #         default_middleware: true
        #         middleware: {  }